contact/urls.py
from django.urls import path
from .views import (
    ContactRequestCreateView, 
    contact_home_view,
    contact_req_lookup_view, 
)

app_name = "contact"
urlpatterns = [
    path("request", ContactRequestCreateView.as_view(), name="contact-request-view"), 
    path("request/search_res", contact_req_lookup_view, name="contact-request-searched-view"), 
    path("", contact_home_view, name="contact-home-view"),
]

scores/urls.py
from django.urls import path
from .views import (
    dynamic_lookup_view, 
    score_home_view, 
)

app_name = "scores"
urlpatterns = [
    path('<int:id>/', dynamic_lookup_view, name='score-details'),
    path('', score_home_view, name='score-home'),]

testsite/urls.py
from django.contrib import admin
from django.urls import path, include
from pages.views import (
    home_view, 
    honorablementions_view)
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    path('scores/', include('scores.urls')),
    path('admin', admin.site.urls),
    path('', home_view, name='firsr-view'),
    path('home/', home_view, name='home_view'),
    path("honorable_mentions/", honorablementions_view, name="honorablementions-view"),
    path("contact/", include("contact.urls")), 
    path("scoreproj/", include("scoreproj.urls")),
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("favicon.ico"))),
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class ContactRequest(models.Model):
    name = models.CharField(max_length=30, help_text="Your preferred name please")
    title = models.CharField(max_length=10, help_text="Examples: Mr, Ms, Mrs")
    subject = models.CharField(max_length=50, help_text="Try your best to summarize the topic of this message")
    comments = models.TextField(blank=True, null=True, help_text="The rest of your message. Try to be concise")
    email = models.EmailField()
    # the below two field will only be editable for admin
    resolved = models.BooleanField(default=False)
    commentFromAdmin = models.CharField(max_length=100, blank=True)

    def get_absolute_url(self):
        return reverse("contact:contact-home")

contact/forms.py
from django import forms
from .models import ContactRequest
from captcha.fields import ReCaptchaField

class ContactRequestForm(forms.ModelForm):
    captcha = ReCaptchaField()
    class Meta:
        model = ContactRequest
        fields = ("title", "name", "subject", "comments", "email")
        

contact/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views.generic import CreateView
from django.core.exceptions import ObjectDoesNotExist
from .forms import ContactRequestForm
from .models import ContactRequest
from .sendemail import send_email

import datetime

def contact_home_view(request):
    return render(request, "contact/contact_home.html", None)

# creates a request and sends an email to my designated email account

def contact_req_lookup_view(request):
    if request.method == "POST":   
        try:
            id_ = request.POST.get("search")
            obj = ContactRequest.objects.get(id=id_)
        except ValueError: 
            return render(request, "invalid_input.html", {})
        except ObjectDoesNotExist:
            return render(request, "contact/contact_req_not_exist.html", {})
        context = {
            "id": id_, 
            "resolved": obj.resolved, 
            "commentFromAdmin": obj.commentFromAdmin
        }
        return render(request, "contact/contact_req_disp.html", context)
    else:
        return render(request, "invalid_input.html", {})

class ContactRequestCreateView(CreateView):
    template_name = 'contact/contact_request.html'
    form_class = ContactRequestForm
    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(ContactRequest, id=id_)
        
    # not having this html as another path because i don't want people mannually accessing it
    def form_valid(self, form) -> HttpResponse:
        # don't save just yet
        task = form.save(commit=False)
        context = {
            "name": form.cleaned_data["name"], 
            "subject": form.cleaned_data["subject"], 
            "comments": form.cleaned_data["comments"], 
            "email": form.cleaned_data["email"],
            "title": form.cleaned_data["title"], 
            "time": str(datetime.date.today()),
            "id": len(ContactRequest.objects.all()) + 1}
        # if the email was sent succesfully, redirect to success page; else redirect to failure page
        if send_email(context):
            task.save()
            return render(self.request, "contact/contact_request_success.html", context)
        return render(self.request, "contact/fail_to_send_email.html", context)

templates/contact/contact_home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'contact/contact_home.css' %}">

<div class="container top-20" id="contact-container">
    <p>You can: </p>
    <ul class="bottom-10">
        <li class="bottom-10">send me a message by pressing the "contact me" button below</li>
        <li class="bottom-10">Check out the status of your past contacts with the unique id given to you</li>
    </ul>
    <p>For the sake of easiness of organization, the "contact me" form will be the only way to reach out to me for timely response. </p>
    <button type="button" class="btn btn-success btn-md bottom-10 " onclick="location.href='contact/request'">contact me</button>

    <form class="d-flex" method="POST" action="{% url 'contact:contact-request-searched-view' %}">{% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search by id" aria-label="Search" name="search">
        <button class="btn btn-success" type="submit">Search</button>
    </form>
</div>

{% endblock %}

templates/contact/contact_req_disp.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'contact/contact_req_disp.css'%}">
<div class="container top-20" id="main-container">
    <p>Request ID: {{id}}</p>
    <p>
        {% if resolved %}
            Resolved: True <br>
            {% if commentFromAdmin %}
                Comment from Jerry: {{commentFromAdmin}}
            {% endif %}
        {% else %}
            Resolved: False
        {% endif %}
    </p>
</div>


{% endblock %}

templates/contact/contact_req_not_exist.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'contact/contact_req_not_exist.css'%}">
<div class="container top-20" id="main-container">
    <p>There's no request corresponding to the entered id. </p>
</div>

{% endblock %}

templates/contact/contact_request.html
{% extends 'universal_create.html'%}

templates/contact/contact_request_success.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'contact/contact_req_disp.css'%}">
<div class="container top-20" id="main-container">
    <h3>Hi {{name}}</h3>
    <p>Your request has been sent successfully. I'll try to get back to you within 2 business days.</p>
    <p>An email with your request's specifics has been sent to your provided email address.</p>
    <p>You can checkout the status of your request using your unique id: {{id}}</p>
    <h3>Best, Jerry</h3>
</div>
{% endblock %}

templates/contact/email_content.html
<!DOCTYPE html>
<html lang="en">
  <body>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <p>Request created successfully</p>
    <ul class="list-group">
        <li class="list-group-item">Name: {{name}}</li>
        <li class="list-group-item">Title: {{title}}</li>
        <li class="list-group-item">Subject: {{subject}}</li>
        <li class="list-group-item">Comments: {{comments}}</li>
        <li class="list-group-item">Email: {{email}}</li>
        <li class="list-group-item">Unique id of submission: {{id}}</li>
        <li class="list-group-item">Time of submission: {{time}}</li>
      </ul>
    <p>Best, Jerry</p>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>

templates/contact/fail_to_send_email.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'contact/contact_req_disp.css'%}">
<div class="container top-20" id="main-container">
    <h3>Hi {{name}}</h3>
    <p>You're seeing this because an attempt to send an email to your 
        provided account at {{email}} has failed. Please double check if you've entered the correct email address, or retry with another email account. 
    </p>
</div>
{% endblock %}