scoreproj/urls.py
from django.urls import path
from .views import (
    ScoreprojLookupView, 
    scoreproj_searched_view,
)

app_name = "scoreproj"
urlpatterns = [
    path("", ScoreprojLookupView.as_view(), name="scoreproj-lookup-view"),
    path("searched/", scoreproj_searched_view, name="scoreproj-searched-view")
]

scores/urls.py
from django.urls import path
from .views import (
    dynamic_lookup_view, 
    score_home_view, 
)

app_name = "scores"
urlpatterns = [
    path('<int:id>/', dynamic_lookup_view, name='score-details'),
    path('', score_home_view, name='score-home'),]

testsite/urls.py
from django.contrib import admin
from django.urls import path, include
from pages.views import (
    home_view, 
    honorablementions_view)
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    path('scores/', include('scores.urls')),
    path('admin', admin.site.urls),
    path('', home_view, name='firsr-view'),
    path('home/', home_view, name='home_view'),
    path("honorable_mentions/", honorablementions_view, name="honorablementions-view"),
    path("contact/", include("contact.urls")), 
    path("scoreproj/", include("scoreproj.urls")),
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("favicon.ico"))),
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scoreproj/models.py
from django.db import models

# Create your models here.

class ScoreProject(models.Model):
    brass = models.BooleanField(default=True)
    saxophone = models.BooleanField(default=True)
    woodwinds = models.BooleanField(default=True)
    auxpercussion = models.BooleanField(default=True)
    drumset = models.BooleanField(default=True)
    piano = models.BooleanField(default=True)

    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    composer = models.CharField(max_length=100, blank=True)

scoreproj/views.py
from django.shortcuts import render
from django.views import View
from .models import ScoreProject
# Create your views here.
class ScoreprojLookupView(View):
    model = ScoreProject

    def get(self, request, *args, **kwargs):
        return render(request, "scoreproj/scoreproj_lookup.html", {})

# not using a form as my clean method is completely different from what django has by default
def scoreproj_searched_view(request):
    default = {"brass", "saxophone", "woodwinds", "auxpercussion", "drumset", "piano"}
    if request.method == "POST":
        temp, n = request.POST.getlist("instrumentation-include"), len(request.POST.getlist("instrumentation-include"))
        res = []
        for sub in temp:
            if sub not in default:
                # executes only if client-side html is changed. Used to prevent hacking. 
                return render(request, "invalid_input.html", {"input": temp})
        sql_qeury_finale = ""
        has_include = False
        has_exclude = False

        # projects that do include at least one of the includes
        if n > 0:
            sql_query_include = "SELECT * FROM scoreproj_ScoreProject WHERE "
            for i in range(0, n - 1):
                sql_query_include += "{} = True OR ".format(temp[i])
            sql_query_include += "{} = True".format(temp[n - 1])
            has_include = True

        temp2, n2 = request.POST.getlist("instrumentation-exclude"), len(request.POST.getlist("instrumentation-exclude"))
        # projects that do not include any of the excludes
        if n2 > 0:
            sql_query_exclude = "SELECT * FROM scoreproj_ScoreProject WHERE "
            for i in range(0, n2 - 1):
                sql_query_exclude += "{} = False And ".format(temp2[i])
            sql_query_exclude += "{} = False".format(temp2[n2 - 1])
            has_exclude = True

        # construct the resulting query
        if not (has_exclude or has_exclude):
            res = ScoreProject.objects.all()
        elif has_exclude and has_include:
            sql_qeury_finale = sql_query_include + " INTERSECT " + sql_query_exclude + ";"
            res = ScoreProject.objects.raw(sql_qeury_finale)
        elif has_exclude: 
            sql_qeury_finale = sql_query_exclude + ";"
            res = ScoreProject.objects.raw(sql_qeury_finale)
        elif has_include:
            sql_qeury_finale = sql_query_include + ";"
            res = ScoreProject.objects.raw(sql_qeury_finale)
        context = {"object_list": res, "included": temp, "excluded": temp2} 
    else:
        context = {"object_list": ScoreProject.objects.all()}
    return render(request, "scoreproj/scoreproj_searched.html", context)

templates/scoreproj/scoreproj_lookup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'scoreproj/scoreproj_lookup.css' %}">
<section>
    <div class="container top-20 bottom-10" id="main-container">
        <div class="row">
            <div class="col">
                <div class="container" id="intro-container">
                    <p>I have many ongoing projects. You can search with specific criterias from below and if anything seems interesting to you, or if you got the inspiration of 
                        working on something else, feel free to contact me with the name of the project.
                    <p>
                    <p>Here're some useful info: </p>
                        <ul class="bottom-10">
                            <li class="bottom-10"><b>Multi-select is enabled.</b> Hold Ctrl/Cmd for windows/mac to select more than one optoions</li>
                            <p>
                                For instance: if you'd like to find out projects that make use of woodwinds or piano but not drumset, simply select both of woodwinds and 
                                piano from the top scrollpane, and drumset from the bottom scrollpane.
                            </p>
                            <li class="bottom-10"><b>To deselect a selected option</b>, press Ctrl/Cmd and click on it.</li>
                          </ul>
                </div> 
            </div>
            <form action="{% url 'scoreproj:scoreproj-searched-view'%}" method="POST"> {% csrf_token %}
                <div class="col">
                    <div class="form-group">
                        <div class="container" id="select-container">
                            <label id="instrumentation-txt">Include: </label>
                            <select class="form-control bottom-10" name="instrumentation-include" multiple>
                                <option value="brass" data-bs-toggle="tooltip" title="Trumpets, Trombone, Tuba, French Horn, Euphonium, etc">Brass</option>
                                <option value="saxophone" data-bs-toggle="tooltip" title="Alto, Tenor, Bari, etc">Saxophone</option>
                                <option value="woodwinds" data-bs-toggle="tooltip" title="Flute, Oboe, (bass) Clarinet, Bassoon, etc">Other Woodwinds</option>
                                <option value="auxpercussion" data-bs-toggle="tooltip" title="Timpani, small percussions, bongo/conga, etc">Auxilary Percussion</option>
                                <option value="drumset" data-bs-toggle="tooltip" title="any set from 1 pc to standard 4-7 pcs">Drum set</option>
                                <option value="piano" data-bs-toggle="tooltip" title="Piano, synthesizers, keyboard percussion, etc">Keyboard</option>
                            </select>
                            <label class="top-20" id="instrumentation-txt">Exclude: </label>
                            <select class="form-control" name="instrumentation-exclude" multiple>
                                <option value="brass" data-bs-toggle="tooltip" title="Trumpets, Trombone, Tuba, French Horn, Euphonium, etc">Brass</option>
                                <option value="saxophone" data-bs-toggle="tooltip" title="Alto, Tenor, Bari, etc">Saxophone</option>
                                <option value="woodwinds" data-bs-toggle="tooltip" title="Flute, Oboe, (bass) Clarinet, Bassoon, etc">Other Woodwinds</option>
                                <option value="auxpercussion" data-bs-toggle="tooltip" title="Timpani, small percussions, bongo/conga, etc">Auxilary Percussion</option>
                                <option value="drumset" data-bs-toggle="tooltip" title="any set from 1 pc to standard 4-7 pcs">Drum set</option>
                                <option value="piano" data-bs-toggle="tooltip" title="Piano, synthesizers, keyboard percussion, etc">Keyboard</option>
                            </select>
                        </div>
                        <input type="submit" name="save/">
                    </div>
                    
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

templates/scoreproj/scoreproj_searched.html
{% extends 'base.html'%}
{% load static %}
{% block content%}
<link rel="stylesheet" type="text/css" href="{% static 'scoreproj/scoreproj_searched.css' %}">
<div class="container top-20" id="main-container">
    <p><b>You chose to include: </b></p>
    {% if included%}
        <ul class="bottom-10">
            {% for include in included%}
                <li class="bottom-10">{{include}}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>None</p>
    {% endif %}

    <p><b>You chose to exclude: </b></p>
    {% if excluded %}
    <ul class="bottom-10">
        {% for exclude in excluded%}
            <li class="bottom-10">{{exclude}}</li>
        {% endfor %}
    </ul>
    {% else %}
        <p>None</p>
    {% endif %}

    {% if not object_list%}
        <p>No results matched your preference, or no projects found in the database :(</p>
    {% else %}
        <p><b>Scores found: </b></p>
        {% for scoreproj in object_list %}
            <p>
                {{ scoreproj.id}} - {{ scoreproj.composer }} - {{scoreproj.title}}
            </p>
            <p>
                {{ scoreproj.description }}
            </p>
        {% endfor %}
    {% endif %}
</div>
    
{% endblock %}